### PR TITLE
Update background.js

### PR DESCRIPTION
**Pull request by karolkania**
Just a minor fix to return error if the sender ID has not been recognized.

### CODE REVIEW

**Comment by tilfin** [comment]
It is not responded deliberately so that a malware can't scan the senderID.

**Comment by karolkania** [comment]
That makes sense.
On the other hand, there's no way to handle the error if that's not a malware scanning but another extension trying to send the message. 
Perhaps we could consider it an option to choose whether such response should be sent or not, what do you think?

**Comment by tilfin** [comment]
After all, I thought that you had to fork this repository and run it locally to develop the extension integration. Could you actually develop it with the extension you installed from the store?

**Comment by karolkania** [comment]
The top priority was to stick to the original extension from the store, the thing is I got into trouble handling this error so decided to fork and test the easiest solution - this PR is the result of that and only that. Although it's not critical to have it handled at all, I wanted to make it less troublesome for anyone using it (and providing an error that the extension IDs do not match may be quite important imo, my bad I didn't consider malware scanning).
I truly hope to finish what I started and release it to the public soon.

**Comment by karolkania** [comment]
Please have a look at https://github.com/netguru/sync-aws-extend-switch-roles - any feedback is more than welcome!

**Pull request merged**
